/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kimds' at '15/06/14 17:48' with Gradle 2.5-20150605053008+0000
 *
 * @author kimds, @date 15/06/14 17:48
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
